language: c

compiler:
  - gcc
  - clang

dist: xenial

before_script:
  - travis_retry sudo apt-get -y install cmake pkg-config libgnutls-dev zlib1g-dev libcpputest-dev lcov

script:
  - ./tools/build-debian.sh test-patches
  - mkdir build && cd build
  - cmake -DBUILD_DOC=ON -DBUILD_MAN=ON -DBUILD_TESTS=ON -DCODE_COVERAGE=ON ..
  - make VERBOSE=1 -j$(nproc)
  - sudo make install
  - ctest -V

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - weechat-relay-cli --help
  - weechat-relay-cli --license
  - weechat-relay-cli --version

matrix:
  fast_finish: true
